### ISSUE TITLE
junos_config.rollback=0 returns ok even if there is no route to the device  

### ISSUE THREAD

**Issue by habeebperwad** [ansible-collections/junipernetworks.junos#106]
Here is my playbook.
```
---
- name: junos_config.rollback
  hosts: hp_dev
  connection: netconf
  tasks:
    - name: junos_config.rollback
      junos_config:
        rollback: "{{ commit_id }}"
```
If the value of commit_id=10, it throws error due to not able to connect to the junos device.
For commit_id=0, it outputs  runner_on_ok event

I see a code [IF NUMBER](https://github.com/ansible-collections/junipernetworks.junos/blob/5b1049e9a9fe8f19bfbe917452e150b3bbd4cda4/plugins/modules/junos_config.py#L442), and here the number can be zero. I am not sure it is the issue.
