### ISSUE TITLE
feature request: l3_interface option in junos_vlans

### ISSUE THREAD

**Issue by eleksis** [ansible-collections/junipernetworks.junos#109]
##### SUMMARY

In order to migrate from deprecated module (junos_vlan), `l3_interface` option should be implemented in new module.

##### ISSUE TYPE
- Feature Idea
```
  l3_interface:
    description:
    - Name of logical layer 3 interface.
    type: str
```
##### COMPONENT NAME

junos_vlans.py

##### ADDITIONAL INFORMATION

Same functionality as in old module.

```yaml

```
