### ISSUE TITLE
feature request: confirm option in all modules

### ISSUE THREAD

**Issue by eleksis** [ansible-collections/junipernetworks.junos#110]
##### SUMMARY

Currently each junos module commits changes right away. If playbook executes multiple junos modules in a row, we don't have an option to revert changes at the end of playbook if we are left with undesired configuration. Example below.

Since junos_config module already has 'confirm' feature, would be nice to add it to all other modules. We are using overridden modules with this feature already. Implementation is simple, I can help if get a green light.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

junos_*.py

##### ADDITIONAL INFORMATION

Playbook example:

```yaml
- name: Configure Juniper switch
  hosts: junos
  tasks:
    - name: Create vlan configuration
      junos_vlans:
        config: "{{ vlans }}"
        state: replaced
        confirm: 3
    - name: Configure switchport parameteres of L2 interfaces
      junos_l2_interfaces:
        config: "{{ l2_interfaces|junos_l2_interfaces_filter }}"
        state: replaced
        confirm: 3
    - name: Configure general settings of L2 interfaces
      junos_interface:
        aggregate: "{{ l2_interfaces|include_keys(['description', 'enabled', 'mtu']) }}"
        confirm: 3

    - name: Confirm last commit
      junos_config:
        confirm_commit: yes
      changed_when: false
```
