### ISSUE TITLE
comma in a string wrongly acting as a separator

### ISSUE THREAD

**Issue by kimjihwan0208** [ansible-collections/junipernetworks.junos#125]
##### SUMMARY

When a parameter in a module is defined as a dictionary and a single string is passed to it, it divides the string based on comma as separate elements.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

junipernetworks.junos.junos_config

##### ANSIBLE VERSION

```paste below
ansible 2.6.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
DEFAULT_JINJA2_EXTENSIONS(/etc/ansible/ansible.cfg) = jinja2.ext.loopcontrols, jinja2.ext.do
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/contrail/config-device-manager/contrail-fabric-ansible-playbooks.log
DEFAULT_LOOKUP_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/lookup_plugins']
DEFAULT_MODULE_UTILS_PATH(/etc/ansible/ansible.cfg) = [u'/etc/module_utils']
DEFAULT_VERBOSITY(/etc/ansible/ansible.cfg) = 0
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Linux node1 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Python 2.7.5

Target witch: qfx-5100-48s

##### STEPS TO REPRODUCE

```yaml
tasks:
  - name: set config
    junipernetworks.junos.junos_config:
      lines: 'set system login message "IT IS, WRONG"'
```

##### EXPECTED RESULTS

The config should have been successfully pushed with the entire string "IT IS, WRONG" set as the login message on the device. 
```
ok: [localhost] => {
    "changed": false, 
    "invocation": {
        "module_args": {
            ...
            "lines": [
                "set system login message \"IT IS, WRONG\""
            ], 
            ...
        }
    }, 
    "msg": "Configuration has been: opened, loaded, checked, diffed, closed."
}
```

##### ACTUAL RESULTS

```paste below
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            ...
            "lines": [
                "set system login message \"IT IS", 
                " WRONG\""
            ], 
           ...
        }
    }, 
    "msg": "Failure loading the configuraton: ConfigLoadError(severity: error, bad_element: WRONG, message: error: unknown command)"
}
```

**Comment by rohitthakur2590** [comment]
@kimjihwan0208 In this case we have to pass this as the list of config `lines` 
```
- name: set config
      junipernetworks.junos.junos_config:
        lines: 
          - 'set system login message "IT IS, NOT WRONG, WHEN USED LIKE THIS"'
```
