### ISSUE TITLE
Add available_network_resources key in junos_facts module

### ISSUE THREAD

**Issue by trishnaguha** [ansible-collections/junipernetworks.junos#160]
- The key will return the list of all the RM resources available for the platform.
- This implementation doesn't affect the current functionality of the junos_facts module and users can use the junos_facts module in the same way as they were before.

Current behavior:
```
---
- name: Fatch facts
  hosts: junos
  gather_facts: no
  collections:
    - junipernetworks.junos
  
  tasks:
    - name: Get basic facts 
      junos_facts:
        gather_subset:
          - '!all'
```
output
```
ok: [192.168.1.63] => {
    "ansible_facts": {
        "ansible_net_api": "netconf",
        "ansible_net_gather_network_resources": [],
        "ansible_net_gather_subset": [
            "default"
        ],
        "ansible_net_hostname": "vsrx",
        "ansible_net_model": "vSRX",
        "ansible_net_python_version": "3.9.2",
        "ansible_net_serialnum": "4a",
        "ansible_net_system": "junos",
        "ansible_net_version": "18.4R1-S3.1",
        "ansible_network_resources": {},
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "available_network_resources": false,
            "config_format": "text",
            "gather_network_resources": null,
            "gather_subset": [
                "!all"
            ],
            "provider": null
        }
    }
}
```
`After implementation of available_network_resources`
`Sample Playbook`:
```
---
- name: Get the list of  available resource Modules
  hosts: junos
  gather_facts: no
  collections:
    - junipernetworks.junos
  
  tasks:
    - name: Get list of avaliable network resources for Junos vSRX and avoid fetching resource facts
      junos_facts:
        gather_subset:
          - '!all'
        available_network_resources: true
```
Result: 
```
ok: [192.168.1.63] => {
    "ansible_facts": {
        "ansible_net_api": "netconf",
        "ansible_net_gather_network_resources": [],
        "ansible_net_gather_subset": [
            "default"
        ],
        "ansible_net_hostname": "vsrx",
        "ansible_net_model": "vSRX",
        "ansible_net_python_version": "3.9.2",
        "ansible_net_serialnum": "4agc",
        "ansible_net_system": "junos",
        "ansible_net_version": "18.4R1-S3.1",
        "ansible_network_resources": {},
        "available_network_resources": [
            "acl_interfaces",
            "acls",
            "bgp_address_family",
            "bgp_global",
            "interfaces",
            "l2_interfaces",
            "l3_interfaces",
            "lacp",
            "lacp_interfaces",
            "lag_interfaces",
            "lldp_global",
            "lldp_interfaces",
            "ospf",
            "ospf_interfaces",
            "ospfv3",
            "static_routes",
            "vlans"
        ],
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "available_network_resources": true,
            "config_format": "text",
            "gather_network_resources": null,
            "gather_subset": [
                "!all"
            ],
            "provider": null
        }
    }
}
```
