### ISSUE TITLE
junipernetworks.junos.junos_interfaces fails when trying to configure AE-interface

### ISSUE THREAD

**Issue by Faddy96** [ansible-collections/junipernetworks.junos#167]
##### SUMMARY

When I try to use the junos_interfaces module to set Description or MTU on an Aggregated Ethernet (AE) interface, the task fails. Works when trying to configure a normal physical interface such as 'ge-0/0/1'.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

junos_interfaces

##### ANSIBLE VERSION

```
ansible --version
ansible 2.10.6
  config file = /home/<user>/gclone/project-network-switch-ports/ansible.cfg
  configured module search path = ['/home/<user>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/<user>/.local/lib/python3.8/site-packages/ansible
  executable location = /home/<user>/.local/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

##### CONFIGURATION

```
ansible-config dump --only-changed
DEFAULT_HOST_LIST(/home/<user>/gclone/project-network-switch-ports/ansible.cfg) = ['/home/<user>/gclone/project-network-switch-ports/hosts']
HOST_KEY_CHECKING(/home/<user>/gclone/project-network-switch-ports/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Running Ansible on Windows using WSLv1 with 'Ubuntu 20.4 LTS'.
Target network devices are Juniper EX3400 switches running 'JUNOS 18.2R3-S4.1 Kernel 32-bit'

##### STEPS TO REPRODUCE

To reproduce, use the junos_interfaces module to try configure an AE-interface.

```
- name: Configure switch interface (Description & MTU)
  vars:
    ansible_command_timeout: 60
  junos_interfaces:
    config:
      - name: ae1
        mtu: 1500
        description: Configured with Ansible
    state: replaced
```

##### EXPECTED RESULTS

If AE-interface does not already exist, expect that the interface will be created. Expected that the AE interface will be configured with MTU set to 1500, and Description set to "Configured with Ansible".

##### ACTUAL RESULTS

Task fails with some Netconf error. I can see error stating "[edit interfaces ae1] - statement not found: description". Configuring description on AE-interfaces uses the exact same syntax as when configuring on a regular ge- or xe-interface.

```
The full traceback is:
  File "/tmp/ansible_junos_interfaces_payload_qt8u1sfb/ansible_junos_interfaces_payload.zip/ansible_collections/junipernetworks/junos/plugins/module_utils/network/junos/junos.py", line 195, in load_configuration
    return conn.load_configuration(
  File "/tmp/ansible_junos_interfaces_payload_qt8u1sfb/ansible_junos_interfaces_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/netconf.py", line 80, in __rpc__
    return self.parse_rpc_error(
  File "/tmp/ansible_junos_interfaces_payload_qt8u1sfb/ansible_junos_interfaces_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/netconf.py", line 121, in parse_rpc_error
    raise ConnectionError(
fatal: [EX3400]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "config": [
                {
                    "description": "Configured with Ansible",
                    "duplex": null,
                    "enabled": true,
                    "hold_time": null,
                    "mtu": 1500,
                    "name": "ae1",
                    "speed": null
                }
            ],
            "running_config": null,
            "state": "replaced"
        }
    },
    "msg": "<?xml version=\"1.0\" encoding=\"UTF-8\"?><rpc-reply xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\" xmlns:junos=\"http://xml.juniper.net/junos/18.2R3/junos\" xmlns:nc=\"urn:ietf:params:xml:ns:netconf:base:1.0\" message-id=\"urn:uuid:87d7ec59-0a8e-41ce-830b-b87072e8fc2d\">\n<load-configuration-results>\n<rpc-error>\n<error-severity>warning</error-severity>\n<error-path>[edit interfaces ae1]</error-path>\n<error-message>statement not found: description</error-message>\n</rpc-error>\n<rpc-error>\n<error-type>protocol</error-type>\n<error-tag>operation-failed</error-tag>\n<error-severity>error</error-severity>\n<error-message>syntax error</error-message>\n<error-info>\n<bad-element>speed</bad-element>\n</error-info>\n</rpc-error>\n<load-error-count>2</load-error-count>\n</load-configuration-results>\n</rpc-reply>"
```

**Comment by rohitthakur2590** [comment]
@DarkCatapulter  junos_interfaces will manage physical interfaces and won't create a new ae interface (which is intended behavior)
You can manage  Link Aggregation Control Protocol (LACP) attributes of interfaces on Juniper JUNOS devices with 
`junos_lacp_interfaces` resource module.
refer: https://docs.ansible.com/ansible/latest/collections/junipernetworks/junos/junos_lacp_interfaces_module.html

**Comment by DarkCatapulter** [comment]
@rohitthakur2590 Thank you for the info. Is there no other way for me to create AE interface through Ansible? Because if not then I will have to create all AE interface beforehand. Reason I want to automate this is because I have 6x Virtual Chassis with 2x48 ports per VC. This means I will likely need to manually configure up to 48 AE interfaces each per VC.

**Comment by eb4x** [comment]
I believe you're looking for `junos_lag_interfaces`

```yaml
- name: configure lag interfaces
  junipernetworks.junos.junos_lag_interfaces:
    config:
      - name: ae0
        mode: passive
        members:
          - member: ge-0/0/0
          - member: ge-0/0/1
          - member: ge-0/0/2
          - member: ge-0/0/3

- name: configure mtu on interfaces
  junipernetworks.junos.junos_interfaces:
    config:
      - name: ae0
        mtu: 9216
```

**Comment by DarkCatapulter** [comment]
@eb4x Thank you for the suggestion, I really appreciate you trying to help. Sadly I have already tried `junos_lag_interfaces` and that doesn't work either if the AE-interface doesn't already exist. My issue is not that I can't configure MTU on an AE interface. What I want to know is if I can use any of the Ansible junos modules for creating a new AE interface on my EX3400 switch(es). Luckily, I think I might've found a solution by accident while trying to re-create the error message that I receive from running the `junos_lag_interfaces` module that you suggested.

I tried running the task below in Ansible. Note that my EX3400 switch doesn't have ae1 configured.
```
---
- name: Configure LAG interfaces with member ports
  vars:
    ansible_command_timeout: 60
  junos_lag_interfaces:
    config:
    - name: ae1
      mode: passive
      members:
        - member: ge-0/0/1
        - member: ge-1/0/1
    state: replaced
```

Here is the output.
```
fatal: [EX3400]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "config": [
                {
                    "link_protection": null,
                    "members": [
                        {
                            "link_type": null,
                            "member": "ge-0/0/1"
                        },
                        {
                            "link_type": null,
                            "member": "ge-1/0/1"
                        }
                    ],
                    "mode": "passive",
                    "name": "ae1"
                }
            ],
            "running_config": null,
            "state": "replaced"
        }
    },
    "msg": "lag interface ae1 not configured, configure interface ae1 before assigning members to lag"
}
```

So even though `junos_lag_interfaces` doesn't work since it requires the AE interface to already be configured, I accidentally ran a task containing `junos_l2_interfaces` and that appears to successfully create an AE interface 😄
