### ISSUE TITLE
junos_config replace not working as expected

### ISSUE THREAD

**Issue by Shourai** [ansible-collections/junipernetworks.junos#172]
##### SUMMARY

What I understand from `update: replace` is that the whole hierarchy level gets replaced by one that the user defines.
However it seems in my test scenarios `replace` acts the same as `merge`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`junos_config`

##### ANSIBLE VERSION

```paste below
ansible 2.10.7
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Target machine version: `Junos: 18.4R2-S5.4`

##### STEPS TO REPRODUCE

```yaml
- name: Configure device
  hosts: junos01
  gather_facts: no
  connection: ansible.netcommon.netconf
  tasks:
  - name: load configure file into device
    junipernetworks.junos.junos_config:
      src: ../../configuration/test.conf
      update: replace
```

##### EXPECTED RESULTS

```
# before
user@junos1> show configuration interfaces
ge-0/0/1 {
    description "Connection 1";
}
ge-0/0/2 {
    description "Connection 2";
}
vme {
    unit 0 {
        family inet {
            dhcp;
        }
    }
}
```
Running junos_config module with the following config:
```
# test.conf
interfaces {
    ge-0/0/1 {
        description "Connection 1";
    }
    vme {
        unit 0 {
            family inet {
                dhcp;
            }
        }
    }
}
```
I expect to see the following result, `ge-0/0/2` removed as that isn't in the interface hierachy anymore.
```
# after
user@junos1> show configuration interfaces
ge-0/0/1 {
    description "Connection 1";
}
vme {
    unit 0 {
        family inet {
            dhcp;
        }
    }
}
```

##### ACTUAL RESULTS

However in actuality what I get is 
```
user@junos1> show configuration interfaces
ge-0/0/1 {
    description "Connection 1";
}
ge-0/0/2 {
    description "Connection 2";
}
vme {
    unit 0 {
        family inet {
            dhcp;
        }
    }
}
```
