### ISSUE TITLE
Merge operation failed when configuring bgp_address_family attribute `aigp`. 

### ISSUE THREAD

**Issue by rohitthakur2590** [ansible-collections/junipernetworks.junos#186]
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
  config file = /home/rothakur/ansible_playbooks/collections/network/juniper/junos/ansible.cfg
  configured module search path = ['/home/rothakur/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/rothakur/dev-workspace/ansible/lib/ansible
  executable location = /home/rothakur/dev-workspace/ansible/bin/ansible
  python version = 3.8.8 (default, Feb 20 2021, 00:00:00) [GCC 10.2.1 20201125 (Red Hat 10.2.1-9)]

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
    - name: test_junos_bgp_address_family_config_005
      junos_bgp_address_family:
        config:
          address_family:
            - afi: 'evpn'
              af_type:
                - type: 'signaling'
                  aigp:
                    set: true
```

##### ACTUAL RESULTS

```paste below
    "msg": "<?xml version=\"1.0\" encoding=\"UTF-8\"?><nc:rpc-reply xmlns:junos=\"http://xml.juniper.net/junos/18.4R1/junos\" xmlns:nc=\"urn:ietf:params:xml:ns:netconf:base:1.0\" message-id=\"urn:uuid:47226321-4de1-445c-b881-01afced15923\">\n<load-configuration-results action=\"merge\" format=\"xml\">\n<nc:rpc-error>\n<nc:error-type>protocol</nc:error-type>\n<nc:error-tag>operation-failed</nc:error-tag>\n<nc:error-severity>error</nc:error-severity>\n<nc:error-message>syntax error</nc:error-message>\n<nc:error-info>\n<nc:bad-element>labeled-unicast</nc:bad-element>\n</nc:error-info>\n</nc:rpc-error>\n<nc:rpc-error>\n<nc:error-type>protocol</nc:error-type>\n<nc:error-tag>operation-failed</nc:error-tag>\n<nc:error-severity>error</nc:error-severity>\n<nc:error-message>syntax error</nc:error-message>\n<nc:error-info>\n<nc:bad-element>labeled-unicast</nc:bad-element>\n</nc:error-info>\n</nc:rpc-error>\n<load-error-count>2</load-error-count>\n</load-configuration-results>\n</nc:rpc-reply>"
}


```
