### ISSUE TITLE
Allow management of junos_user uid value

### ISSUE THREAD

**Issue by arusso** [ansible-collections/junipernetworks.junos#188]
##### SUMMARY

When using the junos_user module we should be able to specify the uid of the login user, just like we can when configuring via cli.

##### ISSUE TYPE

- Feature Idea

##### COMPONENT NAME

- junos_user

##### ADDITIONAL INFORMATION

We want to create local account for some users to login even when central auth fails, and would like the uid to be consistent with our central user database.

```yaml
---
- name: provision local user accounts
  hosts: all
  connection: ansible.netcommon.netconf
  gather_facts: False
  vars:
    junos_local_user_accounts:
      - name: arusso
        full_name: "Aaron Russo"
        role: "super-user"
        uid: 1000
        sshkey: "<sshkey>"
    junos_builtin_users:
      - name: helpdesk
        full_name: "Generic Helpdesk R/O login"
        role: read-only
        state: present
        uid: 9999
      - name: network-admin
        full_name: "Network Admin role"
        role: operator
        state: present
        uid: 9990
      - name: super-user
        full_name: "Super User role"
        role: super-user
        state: present
        uid: 1337
  tasks:
    - name: configure local users
      junipernetworks.junos.junos_user:
        users: "{{junos_local_user_accounts+junos_builtin_users}}"
```
