### ISSUE TITLE
Allow authentication  and interface-type configuration for OSPFv2 area interfaces

### ISSUE THREAD

**Issue by rohitthakur2590** [ansible-collections/junipernetworks.junos#208]
##### SUMMARY

authentication could be password-based or md5, need to implement this with in authentication dict which 
at present  only allows `type` and  has following structure :
```
interfaces:
            description:
            - List of interfaces in this area.
            type: list
            elements: dict
            suboptions:
              authentication:
                description: Specify authentication type
                type: dict
                suboptions:
                  type:
                    description:
                    - Type of authentication to use.
                    type: dict
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

junos_ospf
