### ISSUE TITLE
junos_user -- unable to add custom classes

### ISSUE THREAD

**Issue by mvt33h33** [ansible-collections/junipernetworks.junos#218]
##### SUMMARY
Currently the code is limited to the built-in classes and does not allow any custom classes. Since Junos does not allow you to modify its built-in classes, you are forced to create a new class.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
junos_user.py

##### ADDITIONAL INFORMATION

This feature would allow for dynamic user creations by not limiting the user creation only to a list of predefined classes that we are not modifiable. 

CLASS ON SWITCH
```json
{    
    "configuration" : {
       "system" : {
           "login" : {
              "class" : [
                {
                    "name": "<CLASS NAME>",
                    "idle-timeout": 10,
                    "permissions" : ["all"]
                
                }
                ],
                "password" : {
                    "minimum-reuse" : 20,
                    "maximum-lifetime" : 90, 
                    "minimum-length" : 20, 
                    "maximum-length" : 65, 
                    "change-type" : "character-sets", 
                    "minimum-changes" : 5, 
                    "format" : "sha512"
                }
            }
        }
    }
}
```
PLAYBOOK
```yaml
---
- name: Add User
  hosts: all
  connection: netconf
  gather_facts: false

  tasks:
    - name: Add User
      junos_user:
        name: "{{ item.user }}"
        role: "{{ item.user_role }}"
        encrypted_password: "{{ ( item.user_password | password_hash('sha512')) if (item.user_password is defined) else omit }}"
        sshkey: "{{ item.user_sshkey | default(omit) }}"
        state: "{{ item.user_state }}"
      with_items:
        - "{{ users }}"
      no_log: true
```
