### ISSUE TITLE
Inconsistent top level keys for acls in junos wrt other platforms

### ISSUE THREAD

**Issue by KB-perByte** [ansible-collections/junipernetworks.junos#235]
##### SUMMARY

While gathering facts and resuing it as a source of truth facts top-level key for junos_acls is not the same as IOS/XR/NXOS

```yaml
junos_acls:  <------------------------------ top-level key different for JUNOS
-   acls:
    -   aces:
        -   name: ssh_rule
            protocol: tcp
            source:
                port_protocol:
                    eq: ssh
        name: allow_ssh_acl
    -   aces:
        -   destination:
                address: 1.1.1.1/32
            grant: deny
            name: test-lop
            source:
                address: 2.2.2.2/32
        name: from-cisco
    afi: ipv4

```
op for IOSXR
```yaml
acls:
-   acls:
    -   aces:
        -   grant: deny
            log:
                set: true
            sequence: 10
            source:
                address: 1.1.1.1
        -   grant: permit
            sequence: 20
            source:
                any: true
        acl_type: standard
        name: '99'
    -   acl_type: extended
        name: meraki-fqdn-dns
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

junos_acls

##### STEPS TO REPRODUCE

```yaml

  - name: Set acls for protocol based acls config
    junipernetworks.junos.junos_config:
      lines:
      - set firewall family inet filter allow_ssh_acl term ssh_rule from protocol tcp
      - set firewall family inet filter allow_ssh_acl term ssh_rule from source-port ssh

  - name: Set acls for loopback
    junipernetworks.junos.junos_config:
      lines:
      - set firewall family inet filter from-cisco term test-lop from source-address 2.2.2.2/32
      - set firewall family inet filter from-cisco term test-lop from destination-address 1.1.1.2/32
      - set firewall family inet filter from-cisco term test-lop then discard
      - set interfaces ge-0/0/0 unit 0 family inet filter input-list from-cisco
      
    - name: JUNOS - Gather existing acls facts from _any Environment
      junipernetworks.junos.junos_facts:
        gather_network_resources: 
          - acls
      when: ansible_network_os == "junipernetworks.junos.junos"

    - name: JUNOS - Store gathered facts in a flat file - SoT
      copy:
        content: "{{ ansible_network_resources | to_nice_yaml }}"
        dest: "{{ playbook_dir }}/vars/junos.yaml"
      when: ansible_network_os == "junipernetworks.junos.junos"
```

##### EXPECTED RESULTS

```yaml
acls:
-   acls:
    -   aces:
        -   name: ssh_rule
            protocol: tcp
            source:
                port_protocol:
                    eq: ssh
        name: allow_ssh_acl
    -   aces:
        -   destination:
                address: 1.1.1.3/32
            grant: deny
            name: test-lop
            source:
                address: 2.2.2.2/32
        name: from-cisco
    afi: ipv4

```

##### ACTUAL RESULTS

```yaml
junos_acls:
-   acls:
    -   aces:
        -   name: ssh_rule
            protocol: tcp
            source:
                port_protocol:
                    eq: ssh
        name: allow_ssh_acl
    -   aces:
        -   destination:
                address: 1.1.1.3/32
            grant: deny
            name: test-lop
            source:
                address: 2.2.2.2/32
        name: from-cisco
    afi: ipv4

```
