### ISSUE TITLE
How to use the `connection:` task keywork

### ISSUE THREAD

**Issue by webtroter** [ansible-collections/junipernetworks.junos#245]
##### SUMMARY

I am not able to use the `connection:` task keyword. It is also poorly documented.

Looking at the [platform options](https://docs.ansible.com/ansible/latest/network/user_guide/platform_junos.html#connections-available) it seems to explain how to use the `ansible_connection` variable, but not the `connection:` keyword.

Then, I look into the `config` module, under the [deprecated provider option](https://docs.ansible.com/ansible/latest/collections/junipernetworks/junos/junos_config_module.html#parameter-provider), it says to use `connection: netconf` but that doesn't work and might even be invalid. Shouldn't it be ansible.netcommon.netconf ?

After some more testing, my `connection:` keyword now works because I removed the variable `ansible_connection` from the group and task. 

What would be the best way to specify a default connection type (let's say netconf) and override it per task? should I use `connection:` keyword or overriding the variable `ansible_connection`?

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
https://docs.ansible.com/ansible/latest/network/user_guide/platform_junos.html#connections-available

##### ANSIBLE VERSION

```text
ansible --version
ansible [core 2.11.5] 
  config file = /home/lbn/a.vezina/ansible-repo/ansible.cfg
  configured module search path = ['/home/lbn/a.vezina/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/lbn/a.vezina/.virtualenvs/ansible-venv/lib/python3.6/site-packages/ansible
  ansible collection location = /home/lbn/a.vezina/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/lbn/a.vezina/.virtualenvs/ansible-venv/bin/ansible
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
  jinja version = 3.0.2
  libyaml = True
```

**Comment by Qalthos** [comment]
`connection` is not documented anywhere in the Junos docs because it is a task-level key and not a module key, so it is documented [here](https://docs.ansible.com/ansible/latest/reference_appendices/playbooks_keywords.html#task), albeit as you say without much detail.

The `provider` option is doing something completely different, that does not use the connection plugin infrastructure (and in fact predates the network_cli and netconf connection plugins), and also requires `connection: local` to be set to work. Its use is almost entirely vestigial now and would be best ignored.

But your actual issue seems to be that you are getting bitten by the [variable precedence rules](https://docs.ansible.com/ansible/latest/reference_appendices/general_precedence.html). It may be somewhat non-obvious, but variables _always_ override keywords, regardless of the scope of either. The reason that the connection overriding works when you remove the `ansible_connection` variable from inventory is that the keyword is no longer getting overridden by the variable.

The solution, therefore, is not to mix categories of settings unless you have a particular reason to do so. If you want to set a default connection type, you can do it either as a keyword:
```
---
- hosts: junos  # ansible_connection is not set in inventory
  connection: ansible.netcommon.netconf

  tasks:
    - junos_command:
        commands: [...]
      connection: ansible.netcomon.network_cli
```
_or_ as variables
```
---
- hosts: junos  # ansible_connection is set in inventory

  tasks:
    - junos_command:
        commands: [...]
      vars:
        ansible_connection: ansible.netcomon.network_cli
```
but if you use both, the one that sticks is going to be the most specifically scoped variable, even if that is less tightly scoped than a keyword.
