### ISSUE TITLE
junos_logging_global fails if file_size on device is a string (e.g. 5m)

### ISSUE THREAD

**Issue by derekivey** [ansible-collections/junipernetworks.junos#312]
##### SUMMARY
junos_logging_global fails if file_size specified in the device's running configuration is a string (e.g. 5m).

```
fatal: [fw01]: FAILED! => {"changed": false, "msg": "argument 'file_size' is of type <class 'str'> found in 'config -> archive'. and we were unable to convert to int: <class 'str'> cannot be converted to an int"}
```

Example device configuration:

```
set system syslog archive size 5m
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
junos_logging_global

##### ANSIBLE VERSION
```
ansible [core 2.12.4]
  config file = /home/divey/dev/infrastructure-automation/ansible/ansible.cfg
  configured module search path = ['/home/divey/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/divey/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.12 (main, Mar 24 2022, 13:02:21) [GCC 11.2.0]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION
```
ansible-galaxy collection list junipernetworks.junos

# /usr/lib/python3/dist-packages/ansible_collections
Collection            Version
--------------------- -------
junipernetworks.junos 2.9.0 
```

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
Junos: 18.2R3.4

##### STEPS TO REPRODUCE

```yaml
---
# ansible-playbook -i inventories/hosts setup_junos_syslog.yml \
# --extra-vars='target=device' --ask-vault-pass
#
# This playbook sets up syslog on Juniper nodes.

- hosts: '{{ target }}'
  gather_facts: no
  tasks:
    - name: Configure Syslog
      junipernetworks.junos.junos_logging_global:
        config:
          archive:
            file_size: 5242880
            files: 20
          files:
            - name: messages
              any:
                level: "info"
              authorization:
                level: "info"
              match: "!RT_"
              archive:
                file_size: 5242880
                files: 20
          hosts:
            - any:
                level: "notice"
              authorization:
                level: "info"
              name: '{{ syslog_server_ip }}'
              port: '{{ syslog_server_port }}'
              source_address: '{{ syslog_source_ip }}'
          users:
            - name: "*"
              any:
                level: "emergency"
```
##### EXPECTED RESULTS
Configuration should be applied to the device.

##### ACTUAL RESULTS
Ansible fails to apply configuration to the device with the following error:

```
fatal: [fw01]: FAILED! => {"changed": false, "msg": "argument 'file_size' is of type <class 'str'> found in 'config -> archive'. and we were unable to convert to int: <class 'str'> cannot be converted to an int"}
```

Issue can be worked around by manually changing the existing configuration on the device to remove the instances of "5m" and instead specifying 5000000 in the playbook and on the device.
For example:

```
delete system syslog archive size
set system syslog archive size 5000000
```
