### ISSUE TITLE
junos_interfaces module do not enable ports

### ISSUE THREAD

**Issue by BartokIT** [ansible-collections/junipernetworks.junos#336]
##### SUMMARY
After successful disable a port with the `junipernetworks.junos.junos_interfaces` module, the same do not perform the enablement of the ports

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
junipernetworks.junos.junos_interfaces

##### ANSIBLE VERSION
```
ansible [core 2.13.5]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ansible-emip-prd/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/lib64/python3.9/site-packages/ansible
  ansible collection location = /var/lib/automation/playbooks/tips.network/collections
  executable location = /opt/ansible/bin/ansible
  python version = 3.9.6 (default, Aug 11 2021, 06:39:25) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 3.1.2
  libyaml = True

```

##### COLLECTION VERSION
```
Collection            Version
--------------------- -------
junipernetworks.junos 4.0.0
```

##### CONFIGURATION
```
ANSIBLE_FORCE_COLOR(/etc/ansible/ansible.cfg) = True
CALLBACKS_ENABLED(/etc/ansible/ansible.cfg) = ['profile_tasks']
DEFAULT_BECOME_METHOD(/etc/ansible/ansible.cfg) = community.general.sudosu
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
```

##### STEPS TO REPRODUCE

```yaml
- name: Disable the network interface
  junipernetworks.junos.junos_interfaces:
    config:
      - name: "xe/0/46"
        enabled: false
    state: merged

- name: Enable the network interface
  junipernetworks.junos.junos_interfaces:
    config:
      - name: "xe/0/46"
        enabled: true
    state: merged
```
##### EXPECTED RESULTS
The playbook run should disable the port and then enable, showing changed for both tasks

##### ACTUAL RESULTS
The playbook run should disable the port and then enable, but the change is performed only when disabling the port an
```
TASK [emip.host.play : Disable the network interface] ********************************************************************************************************************************
Friday 11 November 2022  10:37:59 +0100 (0:00:01.049)       0:00:03.631 *******
changed: [hostname1] 

TASK [emip.host.play : Enable the network interface] ********************************************************************************************************************************
Friday 11 November 2022  10:38:59 +0200 (0:00:0.149)       0:00:04.631 *******
ok: [hostname1] 
```
