### ISSUE TITLE
Unable to set vxlan vni for vlan using junos_vlans

### ISSUE THREAD

**Issue by ahewittbell** [ansible-collections/junipernetworks.junos#344]
##### SUMMARY

Unable to set a vlan VNI using the vlans submodule. This can be set using the config module.

e.g. set vlans {{ VLAN_NAME }} vxlan vni {{ VNI_ID }}

```yaml
- name: Set VLAN & VNI
  junipernetworks.junos.junos_config:
    lines:
    - set vlans vlan20 vlan-id 20
    - set vlans vlan20 vxlan vni 20
```

##### ISSUE TYPE
- Add vni option to vlan in the  junipernetworks.junos.junos_vlans

##### COMPONENT NAME

junipernetworks.junos.junos_vlans

##### ADDITIONAL INFORMATION

Example playbook of it being used.

```yaml
- name: Create new vlan with vni
  junipernetworks.junos.junos_vlans:
    config:
    - name: vlan20
      vlan_id: 20
      vni_id: 20
```
