### ISSUE TITLE
Issue with junos_package -"You must provide either 'host' or 'sock_fd' value",

### ISSUE THREAD

**Issue by abailey8** [ansible-collections/junipernetworks.junos#347]
I am unable to install junos software on an SRX 300.  I am using ansible core 2.12.10  with version 4.0.0. of the junipernetworks.junos collection. The netconf service is enabled on the SRX and I have junos-eznc installed. Here is my playbook:

```
- hosts: juniper
  connection: local
  vars: 
    junos_bin: junos-srxsme-15.1X49-D170.4-domestic.tgz
    
  tasks:
    - name: Install Package On Remote Device
      junipernetworks.junos.junos_package: 
        src: /home/andrew/software/juniper/{{ junos_bin }}
        reboot: no
```

I get the following error:

> 
>     "changed": false,
>     "module_stderr": "You must provide either 'host' or 'sock_fd' value",
>     "module_stdout": "",
>     "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"
>
