### ISSUE TITLE
Fix in #342 introduced disparity in presentation of structured data.

### ISSUE THREAD

**Issue by roadracer96** [ansible-collections/junipernetworks.junos#355]
##### SUMMARY

Structured data output has historically been in the Jinja friendly format "some_object" versus the less friendly "some-object".  With a "-" requiring quoting.  The original "chassis_sub_module" object was returned with this in mind.  The new objects introduced in #342 are  returned as "chassis-sub-sub-module", "chassis-sub-sub-sub-module" and so-on.  This should follow a standard format. 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

junipernetworks.junos.junos_facts

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.9]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/MERIT/denike/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/MERIT/denike/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Nov 14 2022, 12:59:47) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True

```

##### COLLECTION VERSION

```paste below
Collection            Version
--------------------- -------
junipernetworks.junos 4.1.0  

```

##### CONFIGURATION

```paste below
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 10
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = explicit
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/opt/ansible/netdevices']
DEFAULT_MODULE_NAME(/etc/ansible/ansible.cfg) = raw
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = debug
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = auto_legacy_silent
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 60
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False

```

##### STEPS TO REPRODUCE

Run a playbook using get_facts and -vvv to inspect output.

```yaml
---
- name: Get JunOS Facts
  junipernetworks.junos.junos_facts:
    gather_subset: [ hardware,interfaces ]
    gather_network_resources: [ lacp,lacp_interfaces,lag_interfaces,l2_interfaces,l3_interfaces,interfaces]
  register: facts


```

##### EXPECTED RESULTS

Consistent labeling methods in structured data.

##### ACTUAL RESULTS

Inconsistent labeling methods in structured data.

```paste below

```
