### ISSUE TITLE
Inconsistent top level keys for acls_interfaces in junos wrt other platforms

### ISSUE THREAD

**Issue by KB-perByte** [ansible-collections/junipernetworks.junos#416]
##### SUMMARY

While gathering facts and reusing it as a source of truth facts top-level key for junos_acls_interfaces is not the same as IOS/XR/NXOS
similar issue - https://github.com/ansible-collections/junipernetworks.junos/issues/235
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
- name: Gather resource facts for health check
  junipernetworks.junos.junos_facts:
    gather_network_resources:
      - acl_interfaces
      - acls
  register: acls_health
```

##### EXPECTED RESULTS

```
     acl_interfaces:
      - access_groups:
        - acls:
          - direction: in
            name: allow_ssh_acl
          afi: ipv4
        name: ge-1/0/0
```

##### ACTUAL RESULTS

```paste below
     junos_acl_interfaces:
      - access_groups:
        - acls:
          - direction: in
            name: allow_ssh_acl
          afi: ipv4
        name: ge-1/0/0
```
