### ISSUE TITLE
Layer2 su

### ISSUE THREAD

**Issue by roadracer96** [ansible-collections/junipernetworks.junos#457]
##### SUMMARY

On a JunOS device using SP style configuration of layer-2 interfaces, a vlan id defined as such:

vlans {
    timtest {
        vlan-id 100;
        interface ge-0/0/0.100;
    }
}
interfaces {
    ge-0/0/0 {
        flexible-vlan-tagging;
        encapsulation flexible-ethernet-services;
        unit 100 {
            encapsulation vlan-bridge;
            vlan-id 100;
        }
    }
}

On an MX device, the same basic construct is employed except "bridge-domain" is used in place of "vlans"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

junos_l2_interfaces/junos_facts
##### ANSIBLE VERSION

```paste below
N/A
```

##### COLLECTION VERSION

```paste below
# /home/MERIT/denike/.ansible/collections/ansible_collections
Collection            Version
--------------------- -------
junipernetworks.junos 5.0.0  

```

##### CONFIGURATION

```paste below
N/A
```

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

Configure a device with SP style VLAN configuration and run a play using the junos_facts module, querying l2_interfaces.

```yaml
- name: Get JunOS Facts
  junipernetworks.junos.junos_facts:
    gather_subset: [ hardware,interfaces ]
    gather_network_resources: [ lacp,lacp_interfaces,lag_interfaces,l2_interfaces,l3_interfaces,interfaces]
  register: facts
```

##### EXPECTED RESULTS

I would expect the returned dict to be similar in structure to l3_interfaces with the addition of a vlan-id (l3_interfaces should return this in the case of L3 sub-interfaces as well)

##### ACTUAL RESULTS

Interface not returned at all.

```paste below

```
