### ISSUE TITLE
Newbie question - roles

### ISSUE THREAD

**Issue by coloradokb** [ansible-collections/junipernetworks.junos#475]
##### SUMMARY
I apologize for the basic question...I've inherited an ansible playbook that has the following in a task:
```
  name: Apply configuration
  hosts: juniper_hosts
  connection: local
  gather_facts: false
  roles:
    - Juniper.junos
 ...
```
In the container we build we removed the ansible-galaxy install Juniper.junos that sets up this role in favor of ansible-galaxy collection install junipernetworks.junos

Is the install Juniper.junos still needed? I was under the impression this was deprecated. Again, sorry for a pretty basic/dumb question.

##### ISSUE TYPE
- Documentation Report
- Question

##### COMPONENT NAME
Juniper.junos / junipernetworks.junos

##### ANSIBLE VERSION

```
[core 2.14.3]
```
