### ISSUE TITLE
junos_prefix_lists doesnt work with dynamic_db, yet claims support.

### ISSUE THREAD

**Issue by roadracer96** [ansible-collections/junipernetworks.junos#478]
##### SUMMARY

When attempting to create/update a prefix-list with dynamic_db: true, all prefixes are added into the standard configuration and not the dynamic DB.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

junos_prefix_lists
##### ANSIBLE VERSION

```paste below
ansible [core 2.13.8]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/MERIT/denike/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/MERIT/denike/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/MERIT/denike/.ansible/collections:/opt/ansible/collections
  executable location = /home/MERIT/denike/.local/bin/ansible
  python version = 3.8.10 (default, Nov 22 2023, 10:22:35) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True

```

##### COLLECTION VERSION

```paste below
# /opt/ansible/collections/ansible_collections
Collection            Version
--------------------- -------
junipernetworks.junos 5.0.0  

```

##### CONFIGURATION

```paste below
COLLECTIONS_PATHS(/etc/ansible/ansible.cfg) = ['/home/MERIT/denike/.ansible/collections', '/opt/ansible/collections']
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 10
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = explicit
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/opt/ansible/netdevices']
DEFAULT_MODULE_NAME(/etc/ansible/ansible.cfg) = raw
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = debug
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = auto_legacy_silent
INVENTORY_ENABLED(/etc/ansible/ansible.cfg) = ['host_list', 'script', 'auto', 'yaml', 'ini', 'toml', 'netbox.netbox.nb_inventory']
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 300
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False

```

##### STEPS TO REPRODUCE

```yaml
---
- name: Test dynamic DB prefix list
  hosts: device1
  gather_facts: no
  tasks:
  - name: Test prefixlist module
    junipernetworks.junos.junos_prefix_lists:
      config:
        - name: SOMECUSTOMER-V4-BLAH
          address_prefixes:
            - 10.0.0.0/24
            - 10.0.10.0/24
          dynamic_db: true
      state: replaced

```

##### EXPECTED RESULTS

```
    prefix-list SOMECUSTOMER-V4-BLAH {
        dynamic-db;
    }
user@device1> configure dynamic                                        
Entering configuration mode

{master}[edit dynamic]
user@device1# show 
## Last changed: 2023-12-13 09:14:21 CST
policy-options {
    prefix-list SOMECUSTOMER-V4-BLAH {
        1.2.3.0/24;
    }
}

```

##### ACTUAL RESULTS

```paste below
    prefix-list SOMECUSTOMER-V4-BLAH {
        dynamic-db;
        10.0.0.0/24;
        10.0.10.0/24;
    }

```
