### ISSUE TITLE
Support for BGP config to routing-instances

### ISSUE THREAD

**Issue by marcusgc** [ansible-collections/junipernetworks.junos#513]
##### SUMMARY
It would be great to support  BGP protocol under routing-instance (and other protocols as well).

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION
There is already some configuration support for routing-instances in the collection, but it lacks support for protocols. This is important to network segmentation and traffic isolation.

```
- name: Merge provided bgp config with device configuration
  junipernetworks.junos.junos_bgp_global:
    config:
      routing-instance: "test"
      loops: 3
      asdot_notation: true
      accept_remote_nexthop: true
      add_path_display_ipv4_address: true
      advertise_inactive: true
      authentication_algorithm: "md5"
      bgp_error_tolerance:
        malformed_route_limit: 20000000
      bmp:
        monitor: true
      damping: true
      description: "This is configured with Junos_bgp resource module"
      hold_time: 5
      include_mp_next_hop: true
      log_updown: true
      no_advertise_peer_as: true
      no_aggregator_id: true
      no_client_reflect: true
      out_delay: 10
      precision_timers: true
      preference: 2
     groups:
       - name: internal
         out_delay: 8
       - name: external
         out_delay: 9
       - name: inboun
         type: internal
         - export: static-to-bgp
         local_address: 10.2.2.2
         name: ibgp
         neighbors:
           - neighbor_address: 10.1.1.1
         type: internal
    state: merged
```
