### ISSUE TITLE
Disable validation for user ROLE field

### ISSUE THREAD

**Issue by romchi** [ansible-collections/junipernetworks.junos#536]
##### SUMMARY
I have identified an issue with the current validation process for the "class" field in the user login functionality. The system is currently set to validate against a collection code that assumes only default classes are used. However, this is problematic because our devices may employ non-default classes for users.

To address this, I recommend revising the validation logic to accommodate any valid class assigned to a user on the device.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
junipernetworks.junos.junos_user

##### ANSIBLE VERSION
```paste below
ansible [core 2.17.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/rb/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /etc/ansible/collections
  executable location = /usr/sbin/ansible
  python version = 3.12.5 (main, Aug  9 2024, 08:20:41) [GCC 14.2.1 20240805] (/usr/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

##### COLLECTION VERSION
```paste below
# /etc/ansible/collections/ansible_collections
Collection            Version
--------------------- -------
junipernetworks.junos 9.1.0
```

##### CONFIGURATION
<!--- Paste verbatim output from "ansible-config dump --only-changed" between quotes -->
```paste below
$ ansible-config dump --only-changed
CONFIG_FILE() = None
```

##### OS / ENVIRONMENT
```
> show system information 
Model: qfx5120-48y-8c
Family: junos-qfx
Junos: 22.2R3-S4.10
Hostname: switch-qfx-1
```


##### STEPS TO REPRODUCE
```yaml
---
- name: Manage users
  hosts: all

  tasks:
    - name: Recreate class backup
      junipernetworks.junos.junos_config:
        lines:
          - "delete system login class backup"
          - "set system login class backup permissions [ firewall routing secret security system view view-configuration ]"
        comment: "recreate class backup"
        check_commit: false

    - name: Create users
      junipernetworks.junos.junos_user:
        name: "oxidized"
        full_name: "Backup System"
        encrypted_password: "$y$j9T$B7ZTLb/4rZmxInRDZNeIx1$hTBbbCgpm7GrrMwMxIPnGY1mOCO6N01eWyK89oaGKZ7"
        role: "backup"
        state: "present"                                                                                                                                                                                                                                                            active: true
```

##### EXPECTED RESULTS
Propose that roles which are not included in the default set should not be subject to validation. This change would allow configure and utilize custom roles more effectively, without system interference.

##### ACTUAL RESULTS
```paste below
fatal: [switch-qfx-1]: FAILED! => {"changed": false, "msg": "value of role must be one of: operator, read-only, super-user, unauthorized, got: backup"}
```
