### ISSUE TITLE
junipernetworks.junos.junos_command does not capture the traceroute output

### ISSUE THREAD

**Issue by hmntsharma** [ansible-collections/junipernetworks.junos#543]
##### SUMMARY

The command module is not able to capture the entire traceroute output.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

junipernetworks.junos.junos_command

##### ANSIBLE VERSION

```paste below
ansible [core 2.17.5]
  config file = /home/lab/ansible.cfg
  configured module search path = ['/home/lab/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/lab/vntdvops/lib/python3.11/site-packages/ansible
  ansible collection location = /home/lab/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/lab/vntdvops/bin/ansible
  python version = 3.11.6 (main, Apr 10 2024, 17:26:07) [GCC 13.2.0] (/home/lab/vntdvops/bin/python)
  jinja version = 3.1.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below

# /home/lab/vntdvops/lib/python3.11/site-packages/ansible_collections
Collection            Version
--------------------- -------
junipernetworks.junos 8.0.0
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /home/lab/ansible.cfg
DEFAULT_FORKS(/home/lab/ansible.cfg) = 30
DEFAULT_HOST_LIST(/home/lab/ansible.cfg) = ['/home/lab/inventory/hosts.ini']
DEFAULT_STDOUT_CALLBACK(/home/lab/ansible.cfg) = yaml
DISPLAY_SKIPPED_HOSTS(/home/lab/ansible.cfg) = False
HOST_KEY_CHECKING(/home/lab/ansible.cfg) = False
PAGER(env: PAGER) = less
PERSISTENT_CONNECT_RETRY_TIMEOUT(/home/lab/ansible.cfg) = 30
PERSISTENT_CONNECT_TIMEOUT(/home/lab/ansible.cfg) = 120
```

##### OS / ENVIRONMENT

```paste below
Ubuntu 23.10 (virtual machine in eve-ng)
```

##### STEPS TO REPRODUCE

```yaml
command_set_1:
- traceroute 4.4.4.4 source 1.1.1.1


- name: RUN COMMANDS
  junipernetworks.junos.junos_command:
    commands: 
    - "{{ item }}"
  loop: "{{ command_set_1 }}"
  register: output

- name: DISPLAY THE OUTPUT
  debug:
    msg:
    - "{{ output }}"
  loop: "{{ command_set_1 }}"
  loop_control:
    index_var: idx
```

##### EXPECTED RESULTS

```
juniper@PE1> traceroute 4.4.4.4 source 1.1.1.1
traceroute to 4.4.4.4 (4.4.4.4) from 1.1.1.1, 30 hops max, 52 byte packets
 1  12.0.0.2 (12.0.0.2)  2.314 ms  2.416 ms  1.630 ms
 2  23.0.0.3 (23.0.0.3)  2.497 ms 27.0.0.7 (27.0.0.7)  4.515 ms 23.0.0.3 (23.0.0.3)  2.251 ms
 3  4.4.4.4 (4.4.4.4)  3.482 ms  4.032 ms  3.827 ms
```

##### ACTUAL RESULTS

```paste below
    - ansible_loop_var: item
      changed: false
      failed: false
      invocation:
        module_args:
          commands:
          - traceroute 4.4.4.4 source 1.1.1.1
          display: null
          interval: 1
          match: all
          retries: 10
          rpcs: null
          wait_for: null
      item: traceroute 4.4.4.4 source 1.1.1.1
      stdout:
      - ''
      stdout_lines:
      - - ''

```

**Comment by hmntsharma** [comment]
found a workaround, via junos_rpc

```
- name: TRACEROUTE-MPLS-LDP
  junipernetworks.junos.junos_rpc:    
   rpc: "traceroute-mpls-ldp"    
   args:      
    fec: "4.4.4.4/32"
    no-resolve: true
    source: "1.1.1.1/32"
   output: "text"
  register: output
```

```
- name: TRACEROUTE-MPLS-LDP OUTPUT
  debug:
    msg:
    - "{{ output.xml }}"
 ```
