### ISSUE TITLE
Fatal error with single item in junipernetworks.junos.junos_acls when using prefix_list with a single entry

### ISSUE THREAD

**Issue by ZenJakey** [ansible-collections/junipernetworks.junos#545]
##### SUMMARY

When using a `junipernetworks.junos.junos_acls` module to configure a firewall filter with using a `prefix_list`, if there is only 1 entry, you receive the error:

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

junipernetworks.junos.junos_acls
##### ANSIBLE VERSION

```paste below
ansible [core 2.15.13]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ansible/.local/bin/ansible
  python version = 3.9.20 (main, Sep  9 2024, 00:00:00) [GCC 11.5.0 20240719 (Red Hat 11.5.0-2)] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/ansible/.ansible/collections/ansible_collections
Collection            Version
--------------------- -------
junipernetworks.junos 9.1.0
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /etc/ansible/ansible.cfg
DEFAULT_LOAD_CALLBACK_PLUGINS(/etc/ansible/ansible.cfg) = True
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Model: ex4300-48mp Junos version: 21.2R3.8

##### STEPS TO REPRODUCE

Running the playbook below with nothing configured in `show policy-options prefix-list SSH-ALLOW`, `show firewall family inet filter VTYACCESS`, or `show interfaces lo0.0` will result in this error on the `Merge JUNOS acl` task (second task). 

```yaml
- name: build-acl
  hosts: junos
  gather_facts: false
  connection: ansible.netcommon.netconf
  tasks:
    - name: Make Junos prefix lists
      junipernetworks.junos.junos_prefix_lists:
        config:
          - name: SSH-ALLOW
            address_prefixes:
              - 192.168.0.0/16 #For example
          #- name: dummylist
        state: merged
    - name: Merge JUNOS acl
      junipernetworks.junos.junos_acls:
        config:
          - afi: ipv4
            acls:
              - name: VTYACCESS
                aces:
                  - name: T1
                    destination:
                      port_protocol:
                        eq: ssh
                    source:
                      prefix_list:
                        - name: SSH-ALLOW
                        #- name: dummylist
                    protocol: tcp
                    grant: "permit"
        state: merged
    - name: Merge JUNOS L3 interface filter
      junipernetworks.junos.junos_acl_interfaces:
        config:
          - name: lo0
            access_groups:
              - afi: ipv4
                acls:
                  - name: VTYACCESS
                    direction: in
        state: merged
```

##### EXPECTED RESULTS

The playbook succeeds.

##### ACTUAL RESULTS

The task fails with the output below. It also commits the faulty `show firewall` config, which has caused issues in testing. Even though the committed configuration changes on junos look ok, it still prevented SSH from working, until I added that `dummylist`. Uncommenting those lines with `dummylist`, and starting with a fresh configuration in the touched sections will result in a success.

The issue seems to be with the `prefix_list` field only having one entry.

```paste below
TASK [Merge JUNOS acl] ***************************************************************************************************************************************
task path: /home/ansible/*company-name-redacted*/playbooks/junos/issue_build_acl.yml:14
Loading collection ansible.netcommon from /home/ansible/.ansible/collections/ansible_collections/ansible/netcommon
Loading collection ansible.utils from /home/ansible/.ansible/collections/ansible_collections/ansible/utils
<192.168.100.250> attempting to start connection
<192.168.100.250> using connection plugin ansible.netcommon.netconf
Found ansible-connection at path /home/ansible/.local/bin/ansible-connection
<192.168.100.250> found existing local domain socket, using it!
<192.168.100.250> identified ncclient device handler: junos.
<192.168.100.250> ESTABLISH NETCONF SSH CONNECTION FOR USER: ansible on PORT 830 TO 192.168.100.250 WITH SSH_CONFIG = None
<192.168.100.250> Loading collection ansible.builtin from 
<192.168.100.250> local domain socket path is /home/ansible/.ansible/pc/356d07bafc
<192.168.100.250> Using network group action junipernetworks.junos.junos for junipernetworks.junos.junos_acls
<192.168.100.250> ANSIBLE_NETWORK_IMPORT_MODULES: enabled
<192.168.100.250> ANSIBLE_NETWORK_IMPORT_MODULES: found junipernetworks.junos.junos_acls  at /home/ansible/.ansible/collections/ansible_collections/junipernetworks/junos/plugins/modules/junos_acls.py
<192.168.100.250> ANSIBLE_NETWORK_IMPORT_MODULES: running junipernetworks.junos.junos_acls
<192.168.100.250> ANSIBLE_NETWORK_IMPORT_MODULES: complete
fatal: [192.168.100.250]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "config": [
                {
                    "acls": [
                        {
                            "aces": [
                                {
                                    "destination": {
                                        "address": null,
                                        "port_protocol": {
                                            "eq": "ssh",
                                            "range": null
                                        },
                                        "prefix_list": null
                                    },
                                    "grant": "permit",
                                    "name": "T1",
                                    "protocol": "tcp",
                                    "protocol_options": null,
                                    "source": {
                                        "address": null,
                                        "port_protocol": null,
                                        "prefix_list": {
                                            "name": "SSH-ALLOW"
                                        }
                                    }
                                }
                            ],
                            "name": "VTYACCESS"
                        }
                    ],
                    "afi": "ipv4"
                }
            ],
            "running_config": null,
            "state": "merged"
        }
    },
    "msg": "argument 'prefix_list' is of type <class 'dict'> found in 'config -> acls -> aces -> source'. and we were unable to convert to list: <class 'dict'> cannot be converted to a list"
}

```
