### ISSUE TITLE
support ansible modules redirection

### ISSUE THREAD

**Issue by chidanandpujar** [ansible-collections/junipernetworks.junos#551]
##### SUMMARY
Support modules redirection from junipernetworks.junos to juniper.device.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
junipernetworks.junos
juniper.device

##### ANSIBLE VERSION

```
ansible [core 2.18.3]
  config file = /root/ansible_modules_redirection_test4/ansible-junos-stdlib/ansible_collections/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.12/site-packages/ansible
  ansible collection location = /root/ansible_modules_redirection_test4/ansible-junos-stdlib/ansible_collections
  executable location = /usr/local/bin/ansible
  python version = 3.12.0 (main, Mar  5 2025, 22:49:30) [GCC 9.3.0] (/usr/bin/python3)
  jinja version = 3.1.6
  libyaml = True

root@masterhost:~/ansible_modules_redirection_test4/ansible-junos-stdlib/ansible_collections# python3 --version
Python 3.12.0


```

##### COLLECTION VERSION

```
Collection                               Version
---------------------------------------- -------
juniper.device                           1.0.7  
junipernetworks.junos                    9.1.0  

```

##### CONFIGURATION

```
root@masterhost:~/ansible_modules_redirection_test4/ansible-junos-stdlib/ansible_collections# cat juniper/device/meta/runtime.yml 
requires_ansible: ">=2.15.0"
plugin_routing:
  action:
    junos_facts:
      redirect: juniper.device.facts
    junos_hostname:
      redirect: juniper.device.hostname
    logging_global:
      redirect: juniper.device.logging_global
    command:
      redirect: juniper.device.command
  modules:
    facts:
      redirect: juniper.device.junos_facts 
    hostname:
      redirect: juniper.device.junos_hostname
    logging_global:
      redirect: juniper.device.junos_logging_global
    command:
      redirect: juniper.device.junos_command


root@masterhost:~/ansible_modules_redirection_test4/ansible-junos-stdlib/ansible_collections# cat junipernetworks/junos/meta/runtime.yml
---
requires_ansible: ">=2.15.0"
plugin_routing:
  action:
    junos_facts:
      redirect: juniper.device.facts
    junos_hostname:
      redirect: juniper.device.hostname
    junos_logging_global:
      redirect: juniper.device.junos_logging_global
    junos_command:
      redirect: juniper.device.junos_command
  modules:
    acl_interfaces:
      redirect: juniper.device.junos_acl_interfaces
    acls:
      redirect: juniper.device.junos_acls
    banner:
      redirect: juniper.device.junos_banner
    command:
      redirect: juniper.device.junos_command
    config:
      redirect: juniper.device.junos_config
    junos_facts:
      redirect: juniper.device.junos_facts
    interfaces:
      redirect: juniper.device.junos_interfaces
    l2_interfaces:
      redirect: juniper.device.junos_l2_interfaces
    l3_interfaces:
      redirect: juniper.device.junos_l3_interfaces
    lacp:
      redirect: juniper.device.junos.junos_lacp
    lacp_interfaces:
      redirect: juniper.device.junos_lacp_interfaces
    lag_interfaces:
      redirect: juniper.device.junos_lag_interfaces
    lldp_global:
      redirect: juniper.device.junos_lldp_global
    bgp_global:
      redirect: juniper.device.junos_bgp_global
    bgp_address_family:
      redirect: juniper.device.junos_bgp_address_family
    routing_instances:
      redirect: juniper.device.junos_routing_instances
    prefix_lists:
      redirect: juniper.device.junos_prefix_lists
    junos_logging_global:
      redirect: juniper.device.junos_logging_global
    ntp_global:
      redirect: juniper.device.junos_ntp_global
    security_policies:
      redirect: juniper.device.junos_security_policies
    security_policies_global:
      redirect: juniper.device.junos_security_policies_global
    security_zones:
      redirect: juniper.device.junos_security_zones
    snmp_server:
      redirect: juniper.device.junos_snmp_server
    junos_hostname:
      redirect: juniper.device.junos_hostname
    routing_options:
      redirect: juniper.device.junos_routing_options
    lldp_interfaces:
      redirect: juniper.device.junos_lldp_interfaces
    netconf:
      redirect: juniper.device.junos_netconf
    ospfv2:
      redirect: juniper.device.junos_ospfv2
    ospfv3:
      redirect: juniper.device.junos_ospfv3
    ospf_interfaces:
      redirect: juniper.device.junos_ospf_interfaces
    package:
      redirect: juniper.device.junos_package
    ping:
      redirect: juniper.device.junos_ping
    rpc:
      redirect: juniper.device.junos_rpc
    scp:
      redirect: juniper.device.junos_scp
      deprecation:
        removal_date: "2025-01-01"
        warning_text: See the plugin documentation for more details
    junos_scp:
      deprecation:
        removal_date: "2025-01-01"
        warning_text: See the plugin documentation for more details
    static_routes:
      redirect: juniper.device.junos_static_routes
    system:
      redirect: juniper.device.junos_system
    user:
      redirect: juniper.device.junos_user
    vlans:
      redirect: juniper.device.junos_vlans
    vrf:
      redirect: juniper.device.junos_vrf


```

##### OS / ENVIRONMENT

Hostname: junos_test.foo
Model: mx960
Junos: 22.2R3-S6.4
JUNOS OS Kernel 64-bit  [20241015.5586108_builder_stable_12_222]
JUNOS OS libs [20241015.5586108_builder_stable_12_222]
JUNOS OS runtime [20241015.5586108_builder_stable_12_222]

##### STEPS TO REPRODUCE

```yaml
root@masterhost:~/ansible_modules_redirection_test4/ansible-junos-stdlib/ansible_collections# cat inventory
[junos]
10.220.10.59

[junos:vars]
#ansible_host=10.220.10.59
ansible_network_os=junipernetworks.junos.junos
ansible_ssh_user=root
#ansible_user=root
ansible_ssh_pass=xyz
ansible_ssh_port=22
ansible_connection=ansible.netcommon.netconf
#ansible_connection=juniper.device.pyez
#ansible_connection=local
ansible_network_cli_ssh_type=libssh 

[all:vars]
ansible_python_interpreter=/usr/bin/python3
root@masterhost:~/ansible_modules_redirection_test4/ansible-junos-stdlib/ansible_collections# cat ansible.cfg 
[defaults]
INVENTORY = ./inventory
collections_path=/root/ansible_modules_redirection_test4/ansible-junos-stdlib/ansible_collections/
host_key_checking = False
hash_behaviour=merge
no_log = False

[persistent_connection]
command_timeout =300
connect_timeout = 300
connect_retry_timeout = 300
root@masterhost:~/ansible_modules_redirection_test4/ansible-junos-stdlib/ansible_collections# cat junos_
cat: junos_: No such file or directory
root@masterhost:~/ansible_modules_redirection_test4/ansible-junos-stdlib/ansible_collections# cat junos_facts.yml 
---
- name: Test Junos Facts Module
  hosts: junos
  gather_facts: false
  collections:
    - junipernetworks.junos 
  tasks:
    - name: Gather Junos Facts
      junos_facts:
      register: junos_facts_output

```

```
common action plugin file:

[raw.githubusercontent.com/ansible-collections/junipernetworks.junos/refs/heads/main/plugins/action/junos.py](https://raw.githubusercontent.com/ansible-collections/junipernetworks.junos/refs/heads/main/plugins/action/junos.py)

connection: netconf
                             junos_facts: [documentation_steps/ansible_redirection_netconf_junos_facts.log at main · chidanandpujar/documentation_steps](https://github.com/chidanandpujar/documentation_steps/blob/main/ansible_redirection_netconf_junos_facts.log)
                             junos_hostname: [documentation_steps/ansible_redireciton_netconf_junos_hostname.log at main · chidanandpujar/documentation_steps](https://github.com/chidanandpujar/documentation_steps/blob/main/ansible_redireciton_netconf_junos_hostname.log)
                             junos_logging_global: [documentation_steps/ansible_redirection_netconf_junos_logging_global.log at main · chidanandpujar/documentation_steps](https://github.com/chidanandpujar/documentation_steps/blob/main/ansible_redirection_netconf_junos_logging_global.log)

              connection: network_cli
                            junos_facts:  [documentation_steps/ansible_redirection_test_network_cli_junos_facts.logs at main · chidanandpujar/documentation_steps](https://github.com/chidanandpujar/documentation_steps/blob/main/ansible_redirection_test_network_cli_junos_facts.logs)
                             junos_hostname: [documentation_steps/ansible_redirection_network_cli_junos_hostname.log at main · chidanandpujar/documentation_steps](https://github.com/chidanandpujar/documentation_steps/blob/main/ansible_redirection_network_cli_junos_hostname.log)
                             junos_logging_global: [documentation_steps/ansible_redirection_network_cli_junos_global_logging.log at main · chidanandpujar/documentation_steps](https://github.com/chidanandpujar/documentation_steps/blob/main/ansible_redirection_network_cli_junos_global_logging.log)



root@masterhost:~/ansible_modules_redirection_test4/ansible-junos-stdlib/ansible_collections/juniper/device/plugins/action# ls -lrt
total 56
lrwxrwxrwx 1 root root   30 Mar 23 21:27 table.py -> juniper_junos_common_action.py
lrwxrwxrwx 1 root root   30 Mar 23 21:27 system.py -> juniper_junos_common_action.py
lrwxrwxrwx 1 root root   30 Mar 23 21:27 srx_cluster.py -> juniper_junos_common_action.py
lrwxrwxrwx 1 root root   30 Mar 23 21:27 software.py -> juniper_junos_common_action.py
lrwxrwxrwx 1 root root   30 Mar 23 21:27 rpc.py -> juniper_junos_common_action.py
lrwxrwxrwx 1 root root   30 Mar 23 21:27 pmtud.py -> juniper_junos_common_action.py
lrwxrwxrwx 1 root root   30 Mar 23 21:27 ping.py -> juniper_junos_common_action.py
lrwxrwxrwx 1 root root   30 Mar 23 21:27 jsnapy.py -> juniper_junos_common_action.py
lrwxrwxrwx 1 root root   30 Mar 23 21:27 facts.py -> juniper_junos_common_action.py
lrwxrwxrwx 1 root root   30 Mar 23 21:27 config.py -> juniper_junos_common_action.py
lrwxrwxrwx 1 root root   30 Mar 23 21:27 command.py -> juniper_junos_common_action.py
lrwxrwxrwx 1 root root   30 Apr  2 23:18 hostname -> juniper_junos_common_action.py
lrwxrwxrwx 1 root root   30 Apr  3 02:07 logging_global.py -> juniper_junos_common_action.py
-rw-r--r-- 1 root root 6871 Apr  8 01:42 junos.py
-rw-r--r-- 1 root root 6787 Apr  8 01:42 juniper_junos_common_action.py_redhat
-rwxr-xr-x 1 root root 2351 Apr  8 01:42 file_copy.py
-rwxr-xr-x 1 root root 2350 Apr  8 01:42 juniper_junos_common_action.py_orig
-rw-r--r-- 1 root root 6295 Apr  8 01:42 extract_data.py
drwxr-xr-x 2 root root 4096 Apr 10 22:09 __pycache__
-rw-r--r-- 1 root root 9023 Apr 11 00:21 juniper_junos_common_action.py_merged
-rw-r--r-- 1 root root 6787 Apr 11 00:21 juniper_junos_common_action.py

```

##### ACTUAL RESULTS

```
root@masterhost:~/ansible_modules_redirection_test4/ansible-junos-stdlib/ansible_collections# ansible-playbook -i inventory junos_facts.yml 

PLAY [Test Junos Facts Module] ******************************************************************************************************************************

TASK [Gather Junos Facts] ***********************************************************************************************************************************
fatal: [10.220.10.59]: FAILED! => {"changed": false, "module_stderr": "b'None'", "module_stdout": "", "msg": "MODULE FAILURE: No start of json char found\nSee stdout/stderr for the exact error"}

PLAY RECAP **************************************************************************************************************************************************
10.220.10.59               : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   



```
