### ISSUE TITLE
junos_ospf_interfaces module doesn't render "interface_type"

### ISSUE THREAD

**Issue by tonybourke** [ansible-collections/junipernetworks.junos#558]
##### SUMMARY

 
The junos_ospf_interfaces_module doesn't render a configuration that configures/corresponds the "interface_type" key. Specifying "interface_type" in the module doesn't affect the NETCONF configuration that is sent to the switch. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

junos_ospf_interfaces, specifically "interface_type". 

##### ANSIBLE VERSION

```paste below
ansible [core 2.15.13]
  config file = /home/tony/NERD-Autobox-topologies/junos/clab-junos-switch/ansible.cfg
  configured module search path = ['/home/tony/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/tony/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/tony/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/tony/.local/bin/ansible
  python version = 3.9.18 (main, Jul  3 2024, 00:00:00) [GCC 11.4.1 20231218 (Red Hat 11.4.1-3)] (/usr/bin/python3)
  jinja version = 3.1.6
  libyaml = True
```

##### COLLECTION VERSION

```paste below
[tony@autobox-huge clab-junos-switch]$ ansible-galaxy collection list community.general

# /home/tony/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 10.6.0 

# /home/tony/.local/lib/python3.9/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 7.5.2  
```

##### CONFIGURATION

```paste below
[tony@autobox-huge clab-junos-switch]$ ansible-config dump --only-changed
CONFIG_FILE() = /home/tony/NERD-Autobox-topologies/junos/clab-junos-switch/ansible.cfg
DEFAULT_GATHERING(/home/tony/NERD-Autobox-topologies/junos/clab-junos-switch/ansible.cfg) = explicit
DEFAULT_HOST_LIST(/home/tony/NERD-Autobox-topologies/junos/clab-junos-switch/ansible.cfg) = ['/home/tony/NERD-Autobox-top>
HOST_KEY_CHECKING(/home/tony/NERD-Autobox-topologies/junos/clab-junos-switch/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Alma Linux 9.5, Junos switch 24.4R1.9 virtual (running in vrnet under containerlab)
--- JUNOS 24.4R1.9 Kernel 64-bit  JNPR-15.0-20241104.1ed86e6_buil

##### STEPS TO REPRODUCE

Create a playbook that utilizes the junos_ospf_interfaces module like below: 

```yaml - name: Configure OSPF
      junipernetworks.junos.junos_ospf_interfaces:
        config:
          - name: 'ge-0/0/0.0'
            address_family:
              - afi: 'ipv4'
                processes:
                  area:
                    area_id: '0.0.0.0'
                  interface_type: p2p
          - name: 'ge-0/0/1.0'
            address_family:
              - afi: 'ipv4'
                processes:
                  area:
                    area_id: '0.0.0.0'
                  interface_type: nbma`

If you take a look at the RESTCONF output, you'll see something like this: 

`ok: [junos-leaf2] => {
    "msg": {
        "changed": false,
        "failed": false,
        "rendered": "<nc:protocols xmlns:nc=\"urn:ietf:params:xml:ns:netconf:base:1.0\"><nc:ospf><nc:area><nc:name>0.0.0.0</nc:name><nc:interface><nc:name>ge-0/0/0.0</nc:name></nc:interface></nc:area></nc:ospf></nc:protocols>"
    }
}`

The interface_type is not specified in the RESTCONF message. 




<!--- Paste example playbooks or commands between quotes below -->
```yaml
- name: Configure OSPF
      junipernetworks.junos.junos_ospf_interfaces:
        config:
          - name: 'ge-0/0/0.0'
            address_family:
              - afi: 'ipv4'
                processes:
                  area:
                    area_id: '0.0.0.0'
                  interface_type: p2p
          - name: 'ge-0/0/1.0'
            address_family:
              - afi: 'ipv4'
                processes:
                  area:
                    area_id: '0.0.0.0'
                  interface_type: nbma`
```

##### EXPECTED RESULTS

It should configure OSPF with the p2p or whatever interface type. The module does not, however. 

##### ACTUAL RESULTS

This is the output: 
`        "rendered": "<nc:protocols xmlns:nc=\"urn:ietf:params:xml:ns:netconf:base:1.0\"><nc:ospf><nc:area><nc:name>0.0.0.0</nc:name><nc:interface><nc:name>ge-0/0/0.0</nc:name></nc:interface></nc:area></nc:ospf></nc:protocols>"`

It lacks the interface_type parameter in RESTCONF. 

```paste below

```
