### ISSUE TITLE
Unable to create zone host-inbound-traffic settings on interface-level

### ISSUE THREAD

**Issue by mkyrc** [ansible-collections/junipernetworks.junos#562]
##### SUMMARY

`junos_security_zones` module doesn't support `host_inbound_traffic` per interface basis. It supports only zone-based `junos_security_zones` configuration.

**Supported example:**
```yaml
    - name: Security Zone
      junipernetworks.junos.junos_security_zones:
        config:
          zones:
            - name: zone_src1
              interfaces:
                - ge-0/0/1.91
              host_inbound_traffic: # host_inbound_traffic on zone level settings
                system_services:
                  - all
```

**alternatively (it works):**
```yaml
    - name: Security Zone (set commands)
      junipernetworks.junos.junos_config:
        lines:
          - "set security zones security-zone zone1 host-inbound-traffic protocols all"
          - "set security zones security-zone zone1 host-inbound-traffic system-services all"
```

Per interface settings is not supported (maybe it will be added in future as a new feature):

```yaml
    - name: Security Zone
      junipernetworks.junos.junos_security_zones:
        config:
          zones:
            - name: zone_src1
              interfaces:
                - interface: ge-0/0/1.91 # interface
                  host_inbound_traffic:  # host_inbound_traffice for specific interface
                    system_services:
                      - all
```

**I'd like to use workaround:**

```yaml
    - name: Security Zone (set commands)
      junipernetworks.junos.junos_config:
        lines:
          - "set security zones security-zone zone1 interface ge-0/0/1.91"
          - "set security zones security-zone zone1 interface ge-0/0/1.91 host-inbound-traffic protocols all"
          - "set security zones security-zone zone1 interface ge-0/0/1.91 host-inbound-traffic system-services all"
```
Above commands (workarond) applied by Ansible doesn't works. It fails with error (see below).

**But the same commands applied on CLI are working and device is configured:**
```
# show security zones security-zone zone1 | display set 
set security zones security-zone zone1 interfaces ge-0/0/1.91 host-inbound-traffic system-services all
set security zones security-zone zone1 interfaces ge-0/0/1.91 host-inbound-traffic protocols all
```

**Ansible task ends with error:**
```
TASK [Security Zone (set commands)] ************************************************************************************************************************
fatal: [nkt-fw-vsrx1]: FAILED! => {"changed": false, "msg": "<?xml version=\"1.0\" encoding=\"UTF-8\"?><rpc-reply xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\" xmlns:junos=\"http://xml.juniper.net/junos/23.2R2.21/junos\" xmlns:nc=\"urn:ietf:params:xml:ns:netconf:base:1.0\" message-id=\"urn:uuid:4771afc1-fe07-428b-8a85-7471cc144f25\">\n<load-configuration-results>\n<rpc-error>\n<error-type>protocol</error-type>\n<error-tag>operation-failed</error-tag>\n<error-severity>error</error-severity>\n<error-message>syntax error</error-message>\n<error-info>\n<bad-element>interface</bad-element>\n</error-info>\n</rpc-error>\n<rpc-error>\n<error-type>protocol</error-type>\n<error-tag>operation-failed</error-tag>\n<error-severity>error</error-severity>\n<error-message>syntax error</error-message>\n<error-info>\n<bad-element>interface</bad-element>\n</error-info>\n</rpc-error>\n<rpc-error>\n<error-type>protocol</error-type>\n<error-tag>operation-failed</error-tag>\n<error-severity>error</error-severity>\n<error-message>syntax error</error-message>\n<error-info>\n<bad-element>interface</bad-element>\n</error-info>\n</rpc-error>\n<ok/>\n</load-configuration-results>\n</rpc-reply>"}
```

**XML (from above) shows this:**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"
    xmlns:junos="http://xml.juniper.net/junos/23.2R2.21/junos"
    xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"
    message-id="urn:uuid:4771afc1-fe07-428b-8a85-7471cc144f25">
    <load-configuration-results>
        <rpc-error>
            <error-type>protocol</error-type>
            <error-tag>operation-failed</error-tag>
            <error-severity>error</error-severity>
            <error-message>syntax error</error-message>
            <error-info>
                <bad-element>interface</bad-element>
            </error-info>
        </rpc-error>
        <rpc-error>
            <error-type>protocol</error-type>
            <error-tag>operation-failed</error-tag>
            <error-severity>error</error-severity>
            <error-message>syntax error</error-message>
            <error-info>
                <bad-element>interface</bad-element>
            </error-info>
        </rpc-error>
        <rpc-error>
            <error-type>protocol</error-type>
            <error-tag>operation-failed</error-tag>
            <error-severity>error</error-severity>
            <error-message>syntax error</error-message>
            <error-info>
                <bad-element>interface</bad-element>
            </error-info>
        </rpc-error>
        <ok />
    </load-configuration-results>
</rpc-reply>
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

` junipernetworks.junos.junos_config`
` junipernetworks.junos.junos_security_zones`

##### ANSIBLE VERSION

```paste below
ansible [core 2.18.4]
  config file = None
  configured module search path = ['/home/horol/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/horol/VENVS/saut/lib/python3.12/site-packages/ansible
  ansible collection location = /home/horol/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/horol/VENVS/saut/bin/ansible
  python version = 3.12.3 (main, Feb  4 2025, 14:48:35) [GCC 13.3.0] (/home/horol/VENVS/saut/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection            Version
--------------------- -------
junipernetworks.junos 10.0.0 
```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
CONFIG_FILE() = None

GALAXY_SERVERS:
```

##### OS / ENVIRONMENT

Linux Ubuntu 24

##### STEPS TO REPRODUCE

See above.

The core issue is - how to apply `host-inbound-traffic` on interface-level. It's not supported by `junipernetworks.junos.junos_security_zones` module. Specific configuration (workaround) applied by `junipernetworks.junos.junos_config` module fails, but the same configuration applied to CLI works. I can't find the problem.

##### EXPECTED RESULTS

Configure `host-inbound-traffic` setting under interface.

##### ACTUAL RESULTS

Unable to create `host-inbound-traffic` on interface-level - it works only on zone-level. The attempt configure it by `junipernetworks.junos.junos_config` as commands failed.

**Comment by mkyrc** [comment]
I found the issue: typo! (interface -> interfaces)

Working task:

```yaml
    - name: Security Zone (set commands)
      junipernetworks.junos.junos_config:
        lines:
          - "set security zones security-zone zone1 interfaces ge-0/0/1.91"
          - "set security zones security-zone zone1 interfaces ge-0/0/1.91 host-inbound-traffic protocols all"
          - "set security zones security-zone zone1 interfaces ge-0/0/1.91 host-inbound-traffic system-services all"
```
