### ISSUE TITLE
Allow variables and lookup modules as src for junos_config

### ISSUE THREAD

**Issue by sebastianw** [ansible-collections/junipernetworks.junos#84]
##### SUMMARY
Allow variables (and by that lookup modules) as src for junos_config so that no temporary file is needed.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
junos_config

##### ADDITIONAL INFORMATION
Currently the `src` parameter in the `junos_config` module can only reference a filename on disk and **NOT** a variable or lookup module. To use for example the template engine without temporary files it would be nice if the src parameter could also contain the config itself so it can be used with a template lookup like this for example:

```
- name: load configure file into device
  junos_config:
    src: "{{ lookup('template', 'my_junos_config.j2') }}"
    update: replace
    comment: update config
```
Right now this takes two steps, a) writing the template to temporary file on disk and b) pushing the configuration.
