### ISSUE TITLE
[Junos] unwanted description attribute in  l3_interfaces facts and gathered operation results in traceback

### ISSUE THREAD

**Issue by rohitthakur2590** [ansible-collections/junipernetworks.junos#93]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

junos_l3_interfaces
##### ANSIBLE VERSION

```paste below
ansible 2.10.0.dev0
```

##### CONFIGURATION

```paste below
ansible_network_os=junipernetworks.junos.junos
ansible_connection=ansible.netcommon.netconf
```

##### STEPS TO REPRODUCE

```yaml
- name: "gather facts for junos layer 3 interfaces"
      junipernetworks.junos.junos_l3_interfaces:
        state: gathered
```

##### ACTUAL RESULTS

```paste below
"gathered": [
        {

        {
            "description": "ANSIBLE",
            "ipv4": [
                {
                    "address": "10.8.38.38/24"
                }
            ],
            "name": "fxp0",
            "unit": "0"
        }
    ]
```
